# -*- coding: utf-8 -*-
"""Guess-The-Number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KnacBqedmzewSrAv8PfRgJccb5u41GUA
"""

import random

print('Hello, are you excited to play "Guess the number" game? \nPick a number between 1 - 20 \nYou get 5 tries :)')

num = random.randint(1,20)

for guess_taken in range(1,6):
  print('Take a guess')
  guess = int(input())

  if guess < num:
    print('your number is too low')

  elif guess > num:
    print('your number is too high')

  else:
    break

if guess == num:
  print(f"Wow, you got it! It took you {guess_taken} tries to guess the number {num}!")
else:
  print(f'The correct number is {num}')